// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: core/remote/remote.proto

package remote

import (
	actor "github.com/orbit-w/oactor/core/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *actor.PID `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"` //receiver
	Sender *actor.PID `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Data   []byte     `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *MessageEnvelope) Reset() {
	*x = MessageEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_remote_remote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnvelope) ProtoMessage() {}

func (x *MessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_core_remote_remote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEnvelope.ProtoReflect.Descriptor instead.
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return file_core_remote_remote_proto_rawDescGZIP(), []int{0}
}

func (x *MessageEnvelope) GetTarget() *actor.PID {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MessageEnvelope) GetSender() *actor.PID {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessageEnvelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_core_remote_remote_proto protoreflect.FileDescriptor

var file_core_remote_remote_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x1a, 0x16, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x22, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x06, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x2d, 0x77, 0x2f,
	0x6f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_remote_remote_proto_rawDescOnce sync.Once
	file_core_remote_remote_proto_rawDescData = file_core_remote_remote_proto_rawDesc
)

func file_core_remote_remote_proto_rawDescGZIP() []byte {
	file_core_remote_remote_proto_rawDescOnce.Do(func() {
		file_core_remote_remote_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_remote_remote_proto_rawDescData)
	})
	return file_core_remote_remote_proto_rawDescData
}

var file_core_remote_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_remote_remote_proto_goTypes = []interface{}{
	(*MessageEnvelope)(nil), // 0: remote.MessageEnvelope
	(*actor.PID)(nil),       // 1: actor.PID
}
var file_core_remote_remote_proto_depIdxs = []int32{
	1, // 0: remote.MessageEnvelope.Target:type_name -> actor.PID
	1, // 1: remote.MessageEnvelope.Sender:type_name -> actor.PID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_remote_remote_proto_init() }
func file_core_remote_remote_proto_init() {
	if File_core_remote_remote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_remote_remote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_remote_remote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_remote_remote_proto_goTypes,
		DependencyIndexes: file_core_remote_remote_proto_depIdxs,
		MessageInfos:      file_core_remote_remote_proto_msgTypes,
	}.Build()
	File_core_remote_remote_proto = out.File
	file_core_remote_remote_proto_rawDesc = nil
	file_core_remote_remote_proto_goTypes = nil
	file_core_remote_remote_proto_depIdxs = nil
}
